### ISSUE TITLE
Error al querer crear una noticia

### ISSUE THREAD

**Issue by rodrigomendoza** [adrielparedes/openscore#24]
Al querer crear una noticia con el contenido como muestra el screnshoot adjunto se encuentra un error que impide realizar la acción.
<img width="1680" alt="screen shot 2018-05-08 at 21 39 22" src="https://user-images.githubusercontent.com/9951517/39789793-7b162ef0-5308-11e8-98ad-f988576baba8.png">

**Comment by rodrigomendoza** [comment]
Se probaron distintas cantidad de caracteres sin lograr crear la noticia

**Comment by rodrigomendoza** [comment]
Creé una noticia nueva utilizando como Titulo: a, Autor: a, Texto: a, y la misma se grabó con éxito.
Pero si la modifico agregando contenido como el de la foto da error.
Luego nunca más permite grabar

**Comment by adrielparedes** [comment]
@rodrigomendoza Se arregla el issue, en la próxima versión se sube. Cerrar el verificar.

**Comment by rodrigomendoza** [comment]
Funciona perfecto
