### ISSUE TITLE
La pantalla por defecto de pronósticos no termina nunca de cargar

### ISSUE THREAD

**Issue by rodrigomendoza** [adrielparedes/openscore#25]
https://openscore-ui-openscore.b9ad.pro-us-east-1.openshiftapps.com/#/pronosticos

<img width="1680" alt="screen shot 2018-05-08 at 21 47 33" src="https://user-images.githubusercontent.com/9951517/39789972-747ae42c-5309-11e8-9c02-753dd6c5c7d7.png">

**Comment by adrielparedes** [comment]
Es un tema con la query a la base de datos, lo estamos revisando

**Comment by rodrigomendoza** [comment]
Anduvo!!!
