### ISSUE TITLE
Todos los usuarios tienen como Last Login hace 10 sec. RARO!

### ISSUE THREAD

**Issue by rodrigomendoza** [adrielparedes/openscore#26]
<img width="1402" alt="screen shot 2018-05-08 at 21 50 56" src="https://user-images.githubusercontent.com/9951517/39790055-023995ec-530a-11e8-8261-1a39732df3fa.png">

**Comment by rodrigomendoza** [comment]
Especialmente porque Hendrix está muerto

**Comment by adrielparedes** [comment]
jajajaja, si,. es verdad, la realidad es que ese campo lo tenemos que sacar porque no estamos registrando el ultimo login, o guardarlo, una de dos :p lo voy a dejar como "mejora" para sacarlo despues

**Comment by adrielparedes** [comment]
@rodrigomendoza Corregido, sube en el proximo release. Cerrar issue al verificar.

**Comment by rodrigomendoza** [comment]
no está más la columna
