### ISSUE TITLE
Al presionar Volver en la pantalla de Alta de Noticia en vez de Volver, graba y se queda ahí

### ISSUE THREAD

**Issue by rodrigomendoza** [adrielparedes/openscore#27]
Al presionar Volver en la pantalla de Alta de Noticia en vez de Volver, graba y se queda ahí.
Debería volver y cancelar los cambios realizados, si los mismos no fueron grabados con anterioridad, y regresar al listado de noticias

**Comment by adrielparedes** [comment]
Jajaja, sisi, el error fue mio, tengo que revisar ahi

**Comment by adrielparedes** [comment]
@rodrigomendoza resuelto, se despliega para mañana. Marcar como resuelto al verificar

**Comment by rodrigomendoza** [comment]
funciona
