### ISSUE TITLE
Traducciones incompletas

### ISSUE THREAD

**Issue by sabrinavc** [adrielparedes/openscore#33]
El sitio está todo en inglés pero:
-  al ir a RULES muestra la ruta como: HOME/REGLAMENTO.
-  al ir a PREDICTIONS muestra la ruta como: HOME/PRONOSTICOS (y está sin acento lo que es falta de ortografía si decideran dejarlo en Español)
- -  al ir a NEWS muestra la ruta como: HOME/NOTICIAS.

**Comment by adrielparedes** [comment]
@sabrinavc se sube en el proximo release, por favor verificar correción mañana y cerrar el issue.
