### ISSUE TITLE
Dashboard vs News

### ISSUE THREAD

**Issue by sabrinavc** [adrielparedes/openscore#34]
En DASHBOARD están las notas de TW. 
En NEWS no hay nada.
No hay instrucciones de como subir contenido.

**Comment by adrielparedes** [comment]
@sabrinavc si, lo de twitter todavia no esta muy claro si va a quedar asi. En cuanto a las News, solo pueden subir noticias los que tengan permisos de admin. Se le va a dar permisos a ciertos usuarios para que puedan escribir notas.
